version: "3.9"
services:
  frontend:
    image: vishalpandita/frontend:v1.0.0
    ports:
      - "80:80"    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: needsencryption
    volumes:
      - "dbdata:/var/lib/mysql"
  backend:
    image: vishalpandita/backend:v1.0.0
    expose:
      - "8080"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: needsencryption
      DATABASE_NAME: empdb
      DBHOST: db
volumes:
  dbdata:
