#v1.0.2
version: "3.9"
services:
  frontend:
    image: vishalpandita/frontend:v1.0.1
    ports:
      - "80:80"    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: {MYSQLPASSWD}
    volumes:
      - "dbdata:/var/lib/mysql"
volumes:
  dbdata:
