version: "3.9"
services:
  backend:
    image: vishalpandita/backend:v1.0.1
    expose:
      - "8080"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: needsencryption
      DATABASE_NAME: empdb
      DBHOST: db 
