apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend-canary
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
    env: canary
# [END service]
