apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp-canary
  labels:
    run: nginx-webapp-canary
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: empcrud
    env: canary
  type: LoadBalancer